### PR TITLE
Update RELEASING.md

### PR DESCRIPTION
**Pull request by fernando-nubank**
This was copy/pasted from a template and was missing some updates

### CODE REVIEW

**Comment by gabrielgiussi** [comment]
We have a release github action so manual release shouldn't be necessary anymore, although the action didn't trigger in the last PR merge.
https://github.com/nubank/clj-github/blob/main/.github/workflows/release.yml

**Comment by gabrielgiussi** [comment]
Where is this clj-github? 🤔 
https://clojars.org/search?q=clj-github
https://clojars.org/nubank/clj-github

**Review by phmeier-nubank — APPROVED** [review]
LGTM :shipit:

**Comment by gabrielgiussi** [comment]
Found it!
https://clojars.org/dev.nubank/clj-github/versions/0.4.1

Did you run the release script @fernando-nubank ?

**Review by gabrielgiussi — CHANGES_REQUESTED** [review]
It shouldn't be necessary with the release github action

**Comment by gabrielgiussi** [comment]
Ahhh I got it, the release script is to push a tag and the github action is triggered on tags.
Although I don't understand why we need to do this, can we just push a tag in a github action triggered on new commits on master? Is this to avoid releasing on every merge in case we are just updating docs for example?

**Review by gabrielgiussi — APPROVED** [review]

**Comment by fernando-nubank** [comment]
> Is this to avoid releasing on every merge in case we are just updating docs for example?

you got it :)

**Comment by fernando-nubank** [comment]
> Did you run the release script @fernando-nubank ?

No. I think there is another PR that can be bundled in the new release

**Comment by gabrielgiussi** [comment]
We could have done that, anyway phillip created the tag so we already have a [0.4.1](https://github.com/nubank/clj-github/releases/tag/0.4.1) (just trying to understand the release process)

**Pull request merged**
